let authState = {
    isLoggedIn: false,
    user: null,
    currentMode: 'login'
};

const lessonsData = {
    1: { title: "Lesson 1: Hello World", subtitle: "Your first step into the world of Python.", videoUrl: "", breadcrumb: "Lesson 1", badge: "Module 1", theoryTitle: "Introduction to Print", theoryDesc: "Welcome to CutiePy. In this lesson, we will learn how to communicate with the computer using the print() function. It is the most basic yet powerful tool in your toolkit.", syntax: 'print("Hello, CutiePy!")', defaultCode: 'print("Hello, CutiePy!")', challengeTask: "Write a Python script that calculates 5 + 5 and prints the result to the console.", challengeHint: "You can place mathematical operations directly inside the print() function, like this: print(2 + 2)", expectedResult: "10" },
    2: { title: "Lesson 2: Variables", subtitle: "Storing and managing data in Python.", videoUrl: "", breadcrumb: "Lesson 2", badge: "Module 2", theoryTitle: "Assigning Variables", theoryDesc: "Variables are containers for storing data values. In Python, a variable is created the moment you first assign a value to it using the equals sign.", syntax: 'name = "CutiePy"\nprint(name)', defaultCode: 'x = 10\ny = 20\nprint(x + y)', challengeTask: "Create two variables a = 15 and b = 25, then print their sum.", challengeHint: "Assign numbers to variables and print their sum: a = 5; b = 5; print(a + b)", expectedResult: "40" },
    3: { title: "Lesson 3: Loops", subtitle: "Automating repetitive workflows.", videoUrl: "", breadcrumb: "Lesson 3", badge: "Module 3", theoryTitle: "For Loops", theoryDesc: "Loops allow you to run a block of code multiple times. A for loop in Python is used for iterating over a sequence.", syntax: 'for i in range(3):\n    print(i)', defaultCode: 'for i in range(3):\n    print(i)', challengeTask: "Write a loop that iterates 3 times using range(3) and prints each number.", challengeHint: "Use: for i in range(3): print(i)", expectedResult: "0\n1\n2" },
    4: { title: "Lesson 4: Functions", subtitle: "Structuring modular logic blocks.", videoUrl: "", breadcrumb: "Lesson 4", badge: "Module 4", theoryTitle: "Defining Functions", theoryDesc: "A function is a block of code which only runs when it is called. You can pass data, known as parameters, into a function.", syntax: 'def greet():\n    print("Hello")', defaultCode: 'def say_hello():\n    print("Python is fun")\n\nsay_hello()', challengeTask: "Define a function named run() that prints 'Active' and call it.", challengeHint: "def run():\n    print('Active')\nrun()", expectedResult: "Active" },
        5: { title: "Lesson 5: Objects", subtitle: "Advanced object-oriented programming.", videoUrl: "", breadcrumb: "Lesson 5", badge: "Module 5", theoryTitle: "Classes & Objects", theoryDesc: "Python is an object-oriented programming language. Almost everything in Python is an object, with its properties and methods.", syntax: 'class Code:\n    pass', defaultCode: 'class Python:\n    version = "3.12"\n\nprint(Python.version)', challengeTask: "Create a class named Bot with a property status = 'Online', and print Bot.status.", challengeHint: "class Bot:\n    status = 'Online'\nprint(Bot.status)", expectedResult: "Online" },
    6: { title: "Lesson 6: Conditionals", subtitle: "Make decisions with if, elif, and else.", videoUrl: "", breadcrumb: "Lesson 6", badge: "Module 6", theoryTitle: "Conditional Logic", theoryDesc: "Conditional statements let your program choose what to do based on a value or comparison. They are the foundation of decision-making in Python.", syntax: 'score = 80\nif score >= 60:\n    print("Pass")', defaultCode: 'score = 80\nif score >= 60:\n    print("Pass")', challengeTask: "Print 'Pass' from a condition that checks whether score = 75 is greater than or equal to 60.", challengeHint: "score = 75\nif score >= 60:\n    print('Pass')", expectedResult: "Pass" },
    7: { title: "Lesson 7: Lists", subtitle: "Store and process collections of values.", videoUrl: "", breadcrumb: "Lesson 7", badge: "Module 7", theoryTitle: "Working with Lists", theoryDesc: "Lists keep multiple values in one ordered collection. You can access items by index, add new values, and loop through the collection.", syntax: 'colors = ["red", "blue"]\nprint(colors[0])', defaultCode: 'numbers = [1, 2, 3]\nprint(numbers[1])', challengeTask: "Create a list containing 10, 20, and 30, then print the second item.", challengeHint: "numbers = [10, 20, 30]\nprint(numbers[1])", expectedResult: "20" },
    8: { title: "Lesson 8: Dictionaries", subtitle: "Organize data with key-value pairs.", videoUrl: "", breadcrumb: "Lesson 8", badge: "Module 8", theoryTitle: "Dictionaries & Sets", theoryDesc: "Dictionaries store values under readable keys, making structured data easy to access. Sets help you work with unique values.", syntax: 'user = {"name": "Ada"}\nprint(user["name"])', defaultCode: 'profile = {"role": "Student"}\nprint(profile["role"])', challengeTask: "Create a dictionary with a city key containing 'Jakarta', then print its value.", challengeHint: "place = {'city': 'Jakarta'}\nprint(place['city'])", expectedResult: "Jakarta" },
    9: { title: "Lesson 9: Error Handling", subtitle: "Write programs that handle mistakes gracefully.", videoUrl: "", breadcrumb: "Lesson 9", badge: "Module 9", theoryTitle: "Try & Except", theoryDesc: "Errors can happen while a program runs. try and except blocks let you respond to expected problems without stopping the entire program.", syntax: 'try:\n    value = int("10")\nexcept ValueError:\n    print("Invalid")', defaultCode: 'try:\n    print("Safe")\nexcept:\n    print("Error")', challengeTask: "Write a try block that prints 'Safe' and an except block for errors.", challengeHint: "try:\n    print('Safe')\nexcept:\n    print('Error')", expectedResult: "Safe" },
    10: { title: "Lesson 10: Mini Project", subtitle: "Combine your skills in a practical program.", videoUrl: "", breadcrumb: "Lesson 10", badge: "Module 10", theoryTitle: "Build a Small Program", theoryDesc: "A mini project combines variables, conditions, functions, and data structures. Use this module to turn separate skills into a complete solution.", syntax: 'def greet(name):\n    return "Hello " + name', defaultCode: 'name = "Python"\nprint("Hello " + name)', challengeTask: "Create a variable named language with the value 'Python', then print 'I love Python'.", challengeHint: "language = 'Python'\nprint('I love ' + language)", expectedResult: "I love Python" },
    11: { title: "Lesson 11: Modules", subtitle: "Organize code into reusable files.", videoUrl: "", breadcrumb: "Lesson 11", badge: "Module 11", theoryTitle: "Importing Modules", theoryDesc: "Modules help you organize related code and reuse it across programs. Python includes many useful modules that you can import when needed.", syntax: 'import math\nprint(math.sqrt(16))', defaultCode: 'import math\nprint(math.sqrt(16))', challengeTask: "Import the math module and print the square root of 25.", challengeHint: "import math\nprint(math.sqrt(25))", expectedResult: "5.0" },
    12: { title: "Lesson 12: Final Project", subtitle: "Bring your Python skills together.", videoUrl: "", breadcrumb: "Lesson 12", badge: "Module 12", theoryTitle: "Your Python Toolkit", theoryDesc: "You have learned the foundations of Python. Combine your skills to make a small program that is clear, useful, and uniquely yours.", syntax: 'tasks = ["learn", "build"]\nprint(len(tasks))', defaultCode: 'tasks = ["learn", "build"]\nprint(len(tasks))', challengeTask: "Create a list named skills with 'Python' and 'Logic', then print its length.", challengeHint: "skills = ['Python', 'Logic']\nprint(len(skills))", expectedResult: "2" }
};

let currentLessonId = 1;
let activeChallengeLesson = 1;
let completedLessonsCount = 0;

const challengeFollowUps = [
    { title: 'Quick Check', task: 'Print the word "Ready" to the console.', hint: 'Use: print("Ready")', expectedResult: 'Ready' },
    { title: 'Number Practice', task: 'Calculate 8 + 4 and print the result.', hint: 'Use: print(8 + 4)', expectedResult: '12' },
    { title: 'Message Practice', task: 'Print the text "Python is fun".', hint: 'Text inside print() needs quotation marks.', expectedResult: 'Python is fun' },
    { title: 'Final Check', task: 'Calculate 6 * 5 and print the result.', hint: 'Use: print(6 * 5)', expectedResult: '30' }
];

Object.entries(lessonsData).forEach(([id, lesson]) => {
    lesson.challenges = [
        { title: 'Core Challenge', task: lesson.challengeTask, hint: lesson.challengeHint, expectedResult: lesson.expectedResult },
        ...challengeFollowUps.map(challenge => ({ ...challenge, title: `${lesson.theoryTitle}: ${challenge.title}` }))
    ];
});
